Fixed a bug that caused double parentheses to be null.
appleple/a-table.js pull request #7
Opened 2023-06-16 03:45 UTC by 1000-x-t30

I'm cutting branches because I'm versioning up node and several libraries.

2023-06-16 05:18 UTC, uidev1116 requested changes
修正ありがとうございます。！
2つコメントさせていただいたのでご確認お願いしたいです。！

2023-06-16 05:18 UTC, uidev1116 commented on src/index.js
> +    console.log(this)
@1000-x-t30 
デバックコードは削除お願いします。！

2023-06-16 05:18 UTC, uidev1116 commented on src/index.js
> +          obj.value = html.replace(/{{(.*?)}}/g, '&lcub;&lcub;$1&rcub;&rcub;');
@1000-x-t30 
ありがとうございます。!
2重括弧は対応できてそうですが、3重括弧だとどうなりますでしょうか？？

あと、`replace(/{(.*?)}/g, '&lcub;$1&rcub;')` というコードは全部4箇所ありますが他のところは対応必要ないでしょうか？？

ご確認お願いします。！

2023-06-16 08:28 UTC, 1000-x-t30 commented on src/index.js
> +    console.log(this)
　@uidev1116 
　修正しました！

2023-06-16 08:28 UTC, 1000-x-t30 commented on src/index.js
> +          obj.value = html.replace(/{{(.*?)}}/g, '&lcub;&lcub;$1&rcub;&rcub;');
　@uidev1116 
　修正しました！

2023-06-19 01:34 UTC, uidev1116 commented on src/index.js
> +          obj.value = html.replace(/{{(.*?)}}/g, '&lcub;&lcub;$1&rcub;&rcub;');
@1000-x-t30 
なるほど。！開く括弧と閉じ括弧別々に処理すれば波括弧がいくつあっても大丈夫そうですね。！
ありがとうございます。approve します。！

2023-06-19 01:35 UTC, uidev1116 approved these changes
@1000-x-t30 
修正ありがとうございます。！マージします。！
npm に新しいバージョン（1.5.10）として publish お願いします。！
おそらくターミナルで npm にログインできてれば `npm run patch` でできると思います。！

2023-06-19 01:36 UTC, merged